//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gufel.QrRender.Providers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gufel.QrRender.Providers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Code&quot;: &quot;2&quot;,
        ///    &quot;GraphicID&quot;: &quot;0&quot;,
        ///    &quot;GraphicTypeCode&quot;: &quot;1&quot;,
        ///    &quot;GraphicData&quot;: &quot;&lt;rect x=\&quot;15\&quot; y=\&quot;15\&quot; style=\&quot;fill:none;\&quot; width=\&quot;70\&quot; height=\&quot;70\&quot; /&gt;\r\n&lt;path d=\&quot;M85,0H15H0v15v70v15h15h70h15V85V15V0H85z M85,85H15V15h70V85z\&quot; /&gt;&quot;,
        ///    &quot;TopLeft&quot;: &quot;&quot;,
        ///    &quot;TopRight&quot;: &quot;&quot;,
        ///    &quot;BottomLeft&quot;: &quot;&quot;,
        ///    &quot;GraphicSize&quot;: &quot;100&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;3&quot;,
        ///    &quot;GraphicID&quot;: &quot;1&quot;,
        ///    &quot;GraphicTypeCode&quot;: &quot;1&quot;,
        ///    &quot;GraphicData&quot;: &quot;&lt;path style=\&quot;fill:none;\&quot; d=\&quot;M85,66.221V33.75C85,23.411,76.414,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GraphicData {
            get {
                return ResourceManager.GetString("GraphicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Code&quot;: &quot;1&quot;,
        ///    &quot;BodyColor&quot;: &quot;#000000&quot;,
        ///    &quot;FrameColor&quot;: &quot;#000000&quot;,
        ///    &quot;BallColor&quot;: &quot;#000000&quot;,
        ///    &quot;BackgroundColor&quot;: &quot;#FFFFFF&quot;,
        ///    &quot;QuietZonePixel&quot;: &quot;60&quot;,
        ///    &quot;Frame&quot;: &quot;0&quot;,
        ///    &quot;Ball&quot;: &quot;0&quot;,
        ///    &quot;Body&quot;: &quot;0&quot;,
        ///    &quot;Logo&quot;: &quot;&quot;,
        ///    &quot;Name&quot;: &quot;کلاسيک&quot;,
        ///    &quot;EnName&quot;: &quot;Classic&quot;,
        ///    &quot;BodyColorGradient&quot;: &quot;&quot;,
        ///    &quot;GradientOnEyes&quot;: &quot;&quot;,
        ///    &quot;GradientType&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;2&quot;,
        ///    &quot;BodyColor&quot;: &quot;#113151&quot;,
        ///    &quot;FrameColor&quot;: &quot;#113151&quot;,
        ///    &quot;BallColor&quot;: &quot;#113151&quot;,
        ///    &quot;Background [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
    }
}
